#!/d/sysutils/conda/python
# 2020/07/22
#
# pip install --upgrade mpl_finance
# new version
# pip install --upgrade mplfinance
#
# download data.csv as well

import matplotlib.pyplot as plt
from mpl_finance import candlestick_ohlc
import pandas as pd
import matplotlib.dates as mpl_dates

plt.style.use('ggplot')

# Extracting Data for plotting
data = pd.read_csv('data.csv')
ohlc = data.loc[:, ['Date', 'Open', 'High', 'Low', 'Close']]
ohlc['Date'] = pd.to_datetime(ohlc['Date'])
ohlc['Date'] = ohlc['Date'].apply(mpl_dates.date2num)
ohlc = ohlc.astype(float)
print(ohlc)

# Creating Subplots
fig, ax = plt.subplots()

candlestick_ohlc(ax, ohlc.values, width=0.6, colorup='green', colordown='red', alpha=0.8)

# Setting labels & titles
ax.set_xlabel('Date')
ax.set_ylabel('Price')
fig.suptitle('Daily Candlestick Chart of NIFTY50')
ax.annotate('Enter',xy=(ohlc.values[3][0],ohlc.values[3][3]),
                    xytext=(ohlc.values[3][0]-0.5,ohlc.values[3][3]-30)) 
ax.annotate('Exit',xy=(ohlc.values[8][0],ohlc.values[8][3]),
                   xytext=(ohlc.values[8][0]-0.4,ohlc.values[8][2]+20))
ax.annotate('Enter',xy=(ohlc.values[1][0],ohlc.values[1][3]-10),
                    xytext=(ohlc.values[1][0]-0.5,ohlc.values[1][3]-100), 
                    arrowprops=dict(facecolor='red', shrink=0.02))
# Formatting Date
date_format = mpl_dates.DateFormatter('%d-%m-%Y')
ax.xaxis.set_major_formatter(date_format)
fig.autofmt_xdate()

fig.tight_layout()

plt.show()# -*- coding: utf-8 -*-

